# Generated by Django 2.1.5 on 2019-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('adsid', models.IntegerField()),
                ('nprice', models.CharField(max_length=50)),
                ('btime', models.CharField(max_length=500)),
            ],
        ),
    ]
