# Generated by Django 2.1.5 on 2019-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('cnm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('snm', models.CharField(max_length=100)),
            ],
        ),
    ]
